/**
 * 地区映射配置
 * 将节点名称中的地区关键词映射到标准化的国旗和代码
 */

/** 地区映射表 */
export const REGION_MAP = {
  // 国旗 Emoji
  '🇭🇰': { flag: '🇭🇰', name: 'HK' },
  '🇨🇳': { flag: '🇨🇳', name: 'TW' },
  '🇲🇴': { flag: '🇲🇴', name: 'MO' },
  '🇯🇵': { flag: '🇯🇵', name: 'JP' },
  '🇰🇷': { flag: '🇰🇷', name: 'KR' },
  '🇸🇬': { flag: '🇸🇬', name: 'SG' },
  '🇲🇾': { flag: '🇲🇾', name: 'MY' },
  '🇮🇩': { flag: '🇮🇩', name: 'ID' },
  '🇹🇭': { flag: '🇹🇭', name: 'TH' },
  '🇻🇳': { flag: '🇻🇳', name: 'VN' },
  '🇵🇭': { flag: '🇵🇭', name: 'PH' },
  '🇬🇧': { flag: '🇬🇧', name: 'GB' },
  '🇩🇪': { flag: '🇩🇪', name: 'DE' },
  '🇫🇷': { flag: '🇫🇷', name: 'FR' },
  '🇮🇹': { flag: '🇮🇹', name: 'IT' },
  '🇪🇸': { flag: '🇪🇸', name: 'ES' },
  '🇺🇸': { flag: '🇺🇸', name: 'US' },
  '🇨🇦': { flag: '🇨🇦', name: 'CA' },
  '🇦🇺': { flag: '🇦🇺', name: 'AU' },
  '🇳🇿': { flag: '🇳🇿', name: 'NZ' },
  '🇧🇷': { flag: '🇧🇷', name: 'BR' },
  '🇰🇿': { flag: '🇰🇿', name: 'KZ' },

  // 东亚
  '香港': { flag: '🇭🇰', name: 'HK' },
  'HK': { flag: '🇭🇰', name: 'HK' },
  'Hong Kong': { flag: '🇭🇰', name: 'HK' },
  'HKG': { flag: '🇭🇰', name: 'HK' },
  '台湾': { flag: '🇨🇳', name: 'TW' },
  'TW': { flag: '🇨🇳', name: 'TW' },
  'Taiwan': { flag: '🇨🇳', name: 'TW' },
  'TWN': { flag: '🇨🇳', name: 'TW' },
  '澳门': { flag: '🇲🇴', name: 'MO' },
  'MO': { flag: '🇲🇴', name: 'MO' },
  'Macao': { flag: '🇲🇴', name: 'MO' },
  '日本': { flag: '🇯🇵', name: 'JP' },
  'JP': { flag: '🇯🇵', name: 'JP' },
  'Japan': { flag: '🇯🇵', name: 'JP' },
  'JPN': { flag: '🇯🇵', name: 'JP' },
  '韩国': { flag: '🇰🇷', name: 'KR' },
  'KR': { flag: '🇰🇷', name: 'KR' },
  'Korea': { flag: '🇰🇷', name: 'KR' },
  'KOR': { flag: '🇰🇷', name: 'KR' },

  // 东南亚
  '狮城': { flag: '🇸🇬', name: 'SG' },
  '新加坡': { flag: '🇸🇬', name: 'SG' },
  'SG': { flag: '🇸🇬', name: 'SG' },
  'Singapore': { flag: '🇸🇬', name: 'SG' },
  'SGP': { flag: '🇸🇬', name: 'SG' },
  '马来西亚': { flag: '🇲🇾', name: 'MY' },
  'MY': { flag: '🇲🇾', name: 'MY' },
  'Malaysia': { flag: '🇲🇾', name: 'MY' },
  'MYS': { flag: '🇲🇾', name: 'MY' },
  '印尼': { flag: '🇮🇩', name: 'ID' },
  '印度尼西亚': { flag: '🇮🇩', name: 'ID' },
  'ID': { flag: '🇮🇩', name: 'ID' },
  'Indonesia': { flag: '🇮🇩', name: 'ID' },
  'IDN': { flag: '🇮🇩', name: 'ID' },
  '泰国': { flag: '🇹🇭', name: 'TH' },
  'TH': { flag: '🇹🇭', name: 'TH' },
  'Thailand': { flag: '🇹🇭', name: 'TH' },
  'THA': { flag: '🇹🇭', name: 'TH' },
  '越南': { flag: '🇻🇳', name: 'VN' },
  'VN': { flag: '🇻🇳', name: 'VN' },
  'Vietnam': { flag: '🇻🇳', name: 'VN' },
  'VNM': { flag: '🇻🇳', name: 'VN' },
  '菲律宾': { flag: '🇵🇭', name: 'PH' },
  'PH': { flag: '🇵🇭', name: 'PH' },
  'Philippines': { flag: '🇵🇭', name: 'PH' },
  'PHL': { flag: '🇵🇭', name: 'PH' },
  '柬埔寨': { flag: '🇰🇭', name: 'KH' },
  'KH': { flag: '🇰🇭', name: 'KH' },

  // 南亚
  '印度': { flag: '🇮🇳', name: 'IN' },
  'IN': { flag: '🇮🇳', name: 'IN' },
  'India': { flag: '🇮🇳', name: 'IN' },
  'IND': { flag: '🇮🇳', name: 'IN' },
  '巴基斯坦': { flag: '🇵🇰', name: 'PK' },
  'PK': { flag: '🇵🇰', name: 'PK' },
  'Pakistan': { flag: '🇵🇰', name: 'PK' },
  'PAK': { flag: '🇵🇰', name: 'PK' },

  // 欧洲
  '英国': { flag: '🇬🇧', name: 'GB' },
  'UK': { flag: '🇬🇧', name: 'GB' },
  'GB': { flag: '🇬🇧', name: 'GB' },
  'United Kingdom': { flag: '🇬🇧', name: 'GB' },
  'GBR': { flag: '🇬🇧', name: 'GB' },
  '德国': { flag: '🇩🇪', name: 'DE' },
  'DE': { flag: '🇩🇪', name: 'DE' },
  'Germany': { flag: '🇩🇪', name: 'DE' },
  'DEU': { flag: '🇩🇪', name: 'DE' },
  '法国': { flag: '🇫🇷', name: 'FR' },
  'FR': { flag: '🇫🇷', name: 'FR' },
  'France': { flag: '🇫🇷', name: 'FR' },
  'FRA': { flag: '🇫🇷', name: 'FR' },
  '意大利': { flag: '🇮🇹', name: 'IT' },
  'IT': { flag: '🇮🇹', name: 'IT' },
  'Italy': { flag: '🇮🇹', name: 'IT' },
  'ITA': { flag: '🇮🇹', name: 'IT' },
  '西班牙': { flag: '🇪🇸', name: 'ES' },
  'ES': { flag: '🇪🇸', name: 'ES' },
  'Spain': { flag: '🇪🇸', name: 'ES' },
  'ESP': { flag: '🇪🇸', name: 'ES' },
  '荷兰': { flag: '🇳🇱', name: 'NL' },
  'NL': { flag: '🇳🇱', name: 'NL' },
  'Netherlands': { flag: '🇳🇱', name: 'NL' },
  'NLD': { flag: '🇳🇱', name: 'NL' },
  '波兰': { flag: '🇵🇱', name: 'PL' },
  'PL': { flag: '🇵🇱', name: 'PL' },
  '乌克兰': { flag: '🇺🇦', name: 'UA' },
  'UA': { flag: '🇺🇦', name: 'UA' },
  '保加利亚': { flag: '🇧🇬', name: 'BG' },
  'BG': { flag: '🇧🇬', name: 'BG' },
  'Bulgaria': { flag: '🇧🇬', name: 'BG' },
  'BGR': { flag: '🇧🇬', name: 'BG' },
  '摩尔多瓦': { flag: '🇲🇩', name: 'MD' },
  'MD': { flag: '🇲🇩', name: 'MD' },
  'Moldova': { flag: '🇲🇩', name: 'MD' },
  'MDA': { flag: '🇲🇩', name: 'MD' },
  '圣保罗': { flag: '🇧🇷', name: 'BR' },
  'SP': { flag: '🇧🇷', name: 'BR' },
  'Sao Paulo': { flag: '🇧🇷', name: 'BR' },

  // 北欧
  '瑞典': { flag: '🇸🇪', name: 'SE' },
  'SE': { flag: '🇸🇪', name: 'SE' },
  'Sweden': { flag: '🇸🇪', name: 'SE' },
  'SWE': { flag: '🇸🇪', name: 'SE' },
  '挪威': { flag: '🇳🇴', name: 'NO' },
  'NO': { flag: '🇳🇴', name: 'NO' },
  'Norway': { flag: '🇳🇴', name: 'NO' },
  'NOR': { flag: '🇳🇴', name: 'NO' },
  '芬兰': { flag: '🇫🇮', name: 'FI' },
  'FI': { flag: '🇫🇮', name: 'FI' },
  '丹麦': { flag: '🇩🇰', name: 'DK' },
  'DK': { flag: '🇩🇰', name: 'DK' },
  '冰岛': { flag: '🇮🇸', name: 'IS' },
  'IS': { flag: '🇮🇸', name: 'IS' },

  // 北美
  '美国': { flag: '🇺🇸', name: 'US' },
  'US': { flag: '🇺🇸', name: 'US' },
  'USA': { flag: '🇺🇸', name: 'US' },
  'United States': { flag: '🇺🇸', name: 'US' },
  '加拿大': { flag: '🇨🇦', name: 'CA' },
  'CA': { flag: '🇨🇦', name: 'CA' },
  'Canada': { flag: '🇨🇦', name: 'CA' },
  'CAN': { flag: '🇨🇦', name: 'CA' },
  '墨西哥': { flag: '🇲🇽', name: 'MX' },
  'MX': { flag: '🇲🇽', name: 'MX' },
  'Mexico': { flag: '🇲🇽', name: 'MX' },
  'MEX': { flag: '🇲🇽', name: 'MX' },

  // 大洋洲
  '澳大利亚': { flag: '🇦🇺', name: 'AU' },
  'AU': { flag: '🇦🇺', name: 'AU' },
  'Australia': { flag: '🇦🇺', name: 'AU' },
  'AUS': { flag: '🇦🇺', name: 'AU' },
  '新西兰': { flag: '🇳🇿', name: 'NZ' },
  'NZ': { flag: '🇳🇿', name: 'NZ' },
  'New Zealand': { flag: '🇳🇿', name: 'NZ' },
  'NZL': { flag: '🇳🇿', name: 'NZ' },

  // 其他
  '俄罗斯': { flag: '🇷🇺', name: 'RU' },
  'RU': { flag: '🇷🇺', name: 'RU' },
  'Russia': { flag: '🇷🇺', name: 'RU' },
  'RUS': { flag: '🇷🇺', name: 'RU' },
  '土耳其': { flag: '🇹🇷', name: 'TR' },
  'TR': { flag: '🇹🇷', name: 'TR' },
  'Turkey': { flag: '🇹🇷', name: 'TR' },
  'TUR': { flag: '🇹🇷', name: 'TR' },
  '巴西': { flag: '🇧🇷', name: 'BR' },
  'BR': { flag: '🇧🇷', name: 'BR' },
  'Brazil': { flag: '🇧🇷', name: 'BR' },
  'BRA': { flag: '🇧🇷', name: 'BR' },
  '阿根廷': { flag: '🇦🇷', name: 'AR' },
  'AR': { flag: '🇦🇷', name: 'AR' },
  '南非': { flag: '🇿🇦', name: 'ZA' },
  'ZA': { flag: '🇿🇦', name: 'ZA' },
  '以色列': { flag: '🇮🇱', name: 'IL' },
  'IL': { flag: '🇮🇱', name: 'IL' },
  '伊拉克': { flag: '🇮🇶', name: 'IQ' },
  'IQ': { flag: '🇮🇶', name: 'IQ' },
  '尼日利亚': { flag: '🇳🇬', name: 'NG' },
  'NG': { flag: '🇳🇬', name: 'NG' },
  '瑞士': { flag: '🇨🇭', name: 'CH' },
  '🇸🇦': { flag: '🇸🇦', name: 'SA' },
  '沙特阿拉伯': { flag: '🇸🇦', name: 'SA' },

  // 中亚
  '哈萨克斯坦': { flag: '🇰🇿', name: 'KZ' },
  'KZ': { flag: '🇰🇿', name: 'KZ' },
  'Kazakhstan': { flag: '🇰🇿', name: 'KZ' },
  'KAZ': { flag: '🇰🇿', name: 'KZ' },
  '哈国': { flag: '🇰🇿', name: 'KZ' }
} as const

/** 地区代码类型 */
export type RegionCode = keyof typeof REGION_MAP

/** 地区信息类型 */
export type RegionInfo = typeof REGION_MAP[RegionCode] 