/**
 * 地区映射配置
 * 将节点名称中的地区关键词映射到标准化的国旗和代码
 */

/** 地区映射表 */
export const REGION_MAP = {
  // 国旗 Emoji
  '🇭🇰': { flag: '🇭🇰', name: 'HK', en: 'Hong Kong' },
  '🇨🇳': { flag: '🇨🇳', name: 'TW', en: 'Taiwan' },
  '🇲🇴': { flag: '🇲🇴', name: 'MO', en: 'Macao' },
  '🇯🇵': { flag: '🇯🇵', name: 'JP', en: 'Japan' },
  '🇰🇷': { flag: '🇰🇷', name: 'KR', en: 'Korea' },
  '🇸🇬': { flag: '🇸🇬', name: 'SG', en: 'Singapore' },
  '🇲🇾': { flag: '🇲🇾', name: 'MY', en: 'Malaysia' },
  '🇮🇩': { flag: '🇮🇩', name: 'ID', en: 'Indonesia' },
  '🇹🇭': { flag: '🇹🇭', name: 'TH', en: 'Thailand' },
  '🇻🇳': { flag: '🇻🇳', name: 'VN', en: 'Vietnam' },
  '🇵🇭': { flag: '🇵🇭', name: 'PH', en: 'Philippines' },
  '🇬🇧': { flag: '🇬🇧', name: 'GB', en: 'UK' },
  '🇩🇪': { flag: '🇩🇪', name: 'DE', en: 'Germany' },
  '🇫🇷': { flag: '🇫🇷', name: 'FR', en: 'France' },
  '🇮🇹': { flag: '🇮🇹', name: 'IT', en: 'Italy' },
  '🇪🇸': { flag: '🇪🇸', name: 'ES', en: 'Spain' },
  '🇺🇸': { flag: '🇺🇸', name: 'US', en: 'USA' },
  '🇨🇦': { flag: '🇨🇦', name: 'CA', en: 'Canada' },
  '🇦🇺': { flag: '🇦🇺', name: 'AU', en: 'Australia' },
  '🇳🇿': { flag: '🇳🇿', name: 'NZ', en: 'New Zealand' },
  '🇧🇷': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  '🇰🇿': { flag: '🇰🇿', name: 'KZ', en: 'Kazakhstan' },

  // 东亚
  '香港': { flag: '🇭🇰', name: 'HK', en: 'Hong Kong' },
  'HK': { flag: '🇭🇰', name: 'HK', en: 'Hong Kong' },
  'Hong Kong': { flag: '🇭🇰', name: 'HK', en: 'Hong Kong' },
  'HKG': { flag: '🇭🇰', name: 'HK', en: 'Hong Kong' },
  '台湾': { flag: '🇨🇳', name: 'TW', en: 'Taiwan' },
  'TW': { flag: '🇨🇳', name: 'TW', en: 'Taiwan' },
  'Taiwan': { flag: '🇨🇳', name: 'TW', en: 'Taiwan' },
  'TWN': { flag: '🇨🇳', name: 'TW', en: 'Taiwan' },
  '澳门': { flag: '🇲🇴', name: 'MO', en: 'Macao' },
  'MO': { flag: '🇲🇴', name: 'MO', en: 'Macao' },
  'Macao': { flag: '🇲🇴', name: 'MO', en: 'Macao' },
  '日本': { flag: '🇯🇵', name: 'JP', en: 'Japan' },
  'JP': { flag: '🇯🇵', name: 'JP', en: 'Japan' },
  'Japan': { flag: '🇯🇵', name: 'JP', en: 'Japan' },
  'JPN': { flag: '🇯🇵', name: 'JP', en: 'Japan' },
  '韩国': { flag: '🇰🇷', name: 'KR', en: 'Korea' },
  'KR': { flag: '🇰🇷', name: 'KR', en: 'Korea' },
  'Korea': { flag: '🇰🇷', name: 'KR', en: 'Korea' },
  'KOR': { flag: '🇰🇷', name: 'KR', en: 'Korea' },

  // 东南亚
  '狮城': { flag: '🇸🇬', name: 'SG', en: 'Singapore' },
  '新加坡': { flag: '🇸🇬', name: 'SG', en: 'Singapore' },
  'SG': { flag: '🇸🇬', name: 'SG', en: 'Singapore' },
  'Singapore': { flag: '🇸🇬', name: 'SG', en: 'Singapore' },
  'SGP': { flag: '🇸🇬', name: 'SG', en: 'Singapore' },
  '马来西亚': { flag: '🇲🇾', name: 'MY', en: 'Malaysia' },
  'MY': { flag: '🇲🇾', name: 'MY', en: 'Malaysia' },
  'Malaysia': { flag: '🇲🇾', name: 'MY', en: 'Malaysia' },
  'MYS': { flag: '🇲🇾', name: 'MY', en: 'Malaysia' },
  '印尼': { flag: '🇮🇩', name: 'ID', en: 'Indonesia' },
  '印度尼西亚': { flag: '🇮🇩', name: 'ID', en: 'Indonesia' },
  'ID': { flag: '🇮🇩', name: 'ID', en: 'Indonesia' },
  'Indonesia': { flag: '🇮🇩', name: 'ID', en: 'Indonesia' },
  'IDN': { flag: '🇮🇩', name: 'ID', en: 'Indonesia' },
  '泰国': { flag: '🇹🇭', name: 'TH', en: 'Thailand' },
  'TH': { flag: '🇹🇭', name: 'TH', en: 'Thailand' },
  'Thailand': { flag: '🇹🇭', name: 'TH', en: 'Thailand' },
  'THA': { flag: '🇹🇭', name: 'TH', en: 'Thailand' },
  '越南': { flag: '🇻🇳', name: 'VN', en: 'Vietnam' },
  'VN': { flag: '🇻🇳', name: 'VN', en: 'Vietnam' },
  'Vietnam': { flag: '🇻🇳', name: 'VN', en: 'Vietnam' },
  'VNM': { flag: '🇻🇳', name: 'VN', en: 'Vietnam' },
  '菲律宾': { flag: '🇵🇭', name: 'PH', en: 'Philippines' },
  'PH': { flag: '🇵🇭', name: 'PH', en: 'Philippines' },
  'Philippines': { flag: '🇵🇭', name: 'PH', en: 'Philippines' },
  'PHL': { flag: '🇵🇭', name: 'PH', en: 'Philippines' },
  '柬埔寨': { flag: '🇰🇭', name: 'KH', en: 'Cambodia' },
  'KH': { flag: '🇰🇭', name: 'KH', en: 'Cambodia' },

  // 南亚
  '印度': { flag: '🇮🇳', name: 'IN', en: 'India' },
  'IN': { flag: '🇮🇳', name: 'IN', en: 'India' },
  'India': { flag: '🇮🇳', name: 'IN', en: 'India' },
  'IND': { flag: '🇮🇳', name: 'IN', en: 'India' },
  '巴基斯坦': { flag: '🇵🇰', name: 'PK', en: 'Pakistan' },
  'PK': { flag: '🇵🇰', name: 'PK', en: 'Pakistan' },
  'Pakistan': { flag: '🇵🇰', name: 'PK', en: 'Pakistan' },
  'PAK': { flag: '🇵🇰', name: 'PK', en: 'Pakistan' },

  // 欧洲
  '英国': { flag: '🇬🇧', name: 'GB', en: 'UK' },
  'UK': { flag: '🇬🇧', name: 'GB', en: 'UK' },
  'GB': { flag: '🇬🇧', name: 'GB', en: 'UK' },
  'United Kingdom': { flag: '🇬🇧', name: 'GB', en: 'UK' },
  'GBR': { flag: '🇬🇧', name: 'GB', en: 'UK' },
  '德国': { flag: '🇩🇪', name: 'DE', en: 'Germany' },
  'DE': { flag: '🇩🇪', name: 'DE', en: 'Germany' },
  'Germany': { flag: '🇩🇪', name: 'DE', en: 'Germany' },
  'DEU': { flag: '🇩🇪', name: 'DE', en: 'Germany' },
  '法国': { flag: '🇫🇷', name: 'FR', en: 'France' },
  'FR': { flag: '🇫🇷', name: 'FR', en: 'France' },
  'France': { flag: '🇫🇷', name: 'FR', en: 'France' },
  'FRA': { flag: '🇫🇷', name: 'FR', en: 'France' },
  '意大利': { flag: '🇮🇹', name: 'IT', en: 'Italy' },
  'IT': { flag: '🇮🇹', name: 'IT', en: 'Italy' },
  'Italy': { flag: '🇮🇹', name: 'IT', en: 'Italy' },
  'ITA': { flag: '🇮🇹', name: 'IT', en: 'Italy' },
  '西班牙': { flag: '🇪🇸', name: 'ES', en: 'Spain' },
  'ES': { flag: '🇪🇸', name: 'ES', en: 'Spain' },
  'Spain': { flag: '🇪🇸', name: 'ES', en: 'Spain' },
  'ESP': { flag: '🇪🇸', name: 'ES', en: 'Spain' },
  '荷兰': { flag: '🇳🇱', name: 'NL', en: 'Netherlands' },
  'NL': { flag: '🇳🇱', name: 'NL', en: 'Netherlands' },
  'Netherlands': { flag: '🇳🇱', name: 'NL', en: 'Netherlands' },
  'NLD': { flag: '🇳🇱', name: 'NL', en: 'Netherlands' },
  '波兰': { flag: '🇵🇱', name: 'PL', en: 'Poland' },
  'PL': { flag: '🇵🇱', name: 'PL', en: 'Poland' },
  '乌克兰': { flag: '🇺🇦', name: 'UA', en: 'Ukraine' },
  'UA': { flag: '🇺🇦', name: 'UA', en: 'Ukraine' },
  '保加利亚': { flag: '🇧🇬', name: 'BG', en: 'Bulgaria' },
  'BG': { flag: '🇧🇬', name: 'BG', en: 'Bulgaria' },
  'Bulgaria': { flag: '🇧🇬', name: 'BG', en: 'Bulgaria' },
  'BGR': { flag: '🇧🇬', name: 'BG', en: 'Bulgaria' },
  '摩尔多瓦': { flag: '🇲🇩', name: 'MD', en: 'Moldova' },
  'MD': { flag: '🇲🇩', name: 'MD', en: 'Moldova' },
  'Moldova': { flag: '🇲🇩', name: 'MD', en: 'Moldova' },
  'MDA': { flag: '🇲🇩', name: 'MD', en: 'Moldova' },
  '圣保罗': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  'SP': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  'Sao Paulo': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },

  // 北欧
  '瑞典': { flag: '🇸🇪', name: 'SE', en: 'Sweden' },
  'SE': { flag: '🇸🇪', name: 'SE', en: 'Sweden' },
  'Sweden': { flag: '🇸🇪', name: 'SE', en: 'Sweden' },
  'SWE': { flag: '🇸🇪', name: 'SE', en: 'Sweden' },
  '挪威': { flag: '🇳🇴', name: 'NO', en: 'Norway' },
  'NO': { flag: '🇳🇴', name: 'NO', en: 'Norway' },
  'Norway': { flag: '🇳🇴', name: 'NO', en: 'Norway' },
  'NOR': { flag: '🇳🇴', name: 'NO', en: 'Norway' },
  '芬兰': { flag: '🇫🇮', name: 'FI', en: 'Finland' },
  'FI': { flag: '🇫🇮', name: 'FI', en: 'Finland' },
  '丹麦': { flag: '🇩🇰', name: 'DK', en: 'Denmark' },
  'DK': { flag: '🇩🇰', name: 'DK', en: 'Denmark' },
  '冰岛': { flag: '🇮🇸', name: 'IS', en: 'Iceland' },
  'IS': { flag: '🇮🇸', name: 'IS', en: 'Iceland' },

  // 北美
  '美国': { flag: '🇺🇸', name: 'US', en: 'USA' },
  'US': { flag: '🇺🇸', name: 'US', en: 'USA' },
  'USA': { flag: '🇺🇸', name: 'US', en: 'USA' },
  'United States': { flag: '🇺🇸', name: 'US', en: 'USA' },
  '加拿大': { flag: '🇨🇦', name: 'CA', en: 'Canada' },
  'CA': { flag: '🇨🇦', name: 'CA', en: 'Canada' },
  'Canada': { flag: '🇨🇦', name: 'CA', en: 'Canada' },
  'CAN': { flag: '🇨🇦', name: 'CA', en: 'Canada' },
  '墨西哥': { flag: '🇲🇽', name: 'MX', en: 'Mexico' },
  'MX': { flag: '🇲🇽', name: 'MX', en: 'Mexico' },
  'Mexico': { flag: '🇲🇽', name: 'MX', en: 'Mexico' },
  'MEX': { flag: '🇲🇽', name: 'MX', en: 'Mexico' },

  // 大洋洲
  '澳大利亚': { flag: '🇦🇺', name: 'AU', en: 'Australia' },
  'AU': { flag: '🇦🇺', name: 'AU', en: 'Australia' },
  'Australia': { flag: '🇦🇺', name: 'AU', en: 'Australia' },
  'AUS': { flag: '🇦🇺', name: 'AU', en: 'Australia' },
  '新西兰': { flag: '🇳🇿', name: 'NZ', en: 'New Zealand' },
  'NZ': { flag: '🇳🇿', name: 'NZ', en: 'New Zealand' },
  'New Zealand': { flag: '🇳🇿', name: 'NZ', en: 'New Zealand' },
  'NZL': { flag: '🇳🇿', name: 'NZ', en: 'New Zealand' },

  // 其他
  '俄罗斯': { flag: '🇷🇺', name: 'RU', en: 'Russia' },
  'RU': { flag: '🇷🇺', name: 'RU', en: 'Russia' },
  'Russia': { flag: '🇷🇺', name: 'RU', en: 'Russia' },
  'RUS': { flag: '🇷🇺', name: 'RU', en: 'Russia' },
  '土耳其': { flag: '🇹🇷', name: 'TR', en: 'Turkey' },
  'TR': { flag: '🇹🇷', name: 'TR', en: 'Turkey' },
  'Turkey': { flag: '🇹🇷', name: 'TR', en: 'Turkey' },
  'TUR': { flag: '🇹🇷', name: 'TR', en: 'Turkey' },
  '巴西': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  'BR': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  'Brazil': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  'BRA': { flag: '🇧🇷', name: 'BR', en: 'Brazil' },
  '阿根廷': { flag: '🇦🇷', name: 'AR', en: 'Argentina' },
  'AR': { flag: '🇦🇷', name: 'AR', en: 'Argentina' },
  '南非': { flag: '🇿🇦', name: 'ZA', en: 'South Africa' },
  'ZA': { flag: '🇿🇦', name: 'ZA', en: 'South Africa' },
  '以色列': { flag: '🇮🇱', name: 'IL', en: 'Israel' },
  'IL': { flag: '🇮🇱', name: 'IL', en: 'Israel' },
  '伊拉克': { flag: '🇮🇶', name: 'IQ', en: 'Iraq' },
  'IQ': { flag: '🇮🇶', name: 'IQ', en: 'Iraq' },
  '尼日利亚': { flag: '🇳🇬', name: 'NG', en: 'Nigeria' },
  'NG': { flag: '🇳🇬', name: 'NG', en: 'Nigeria' },
  '瑞士': { flag: '🇨🇭', name: 'CH', en: 'Switzerland' },
  '🇸🇦': { flag: '🇸🇦', name: 'SA', en: 'Saudi Arabia' },
  '沙特阿拉伯': { flag: '🇸🇦', name: 'SA', en: 'Saudi Arabia' },
  '阿联酋': { flag: '🇦🇪', name: 'AE', en: 'United Arab Emirates' },
  'AE': { flag: '🇦🇪', name: 'AE', en: 'United Arab Emirates' },
  'UAE': { flag: '🇦🇪', name: 'AE', en: 'United Arab Emirates' },
  '智利': { flag: '🇨🇱', name: 'CL', en: 'Chile' },
  'CL': { flag: '🇨🇱', name: 'CL', en: 'Chile' },
  'Chile': { flag: '🇨🇱', name: 'CL', en: 'Chile' },
  '匈牙利': { flag: '🇭🇺', name: 'HU', en: 'Hungary' },
  'HU': { flag: '🇭🇺', name: 'HU', en: 'Hungary' },
  'Hungary': { flag: '🇭🇺', name: 'HU', en: 'Hungary' },
  '奥地利': { flag: '🇦🇹', name: 'AT', en: 'Austria' },
  'AT': { flag: '🇦🇹', name: 'AT', en: 'Austria' },
  'Austria': { flag: '🇦🇹', name: 'AT', en: 'Austria' },
  '爱尔兰': { flag: '🇮🇪', name: 'IE', en: 'Ireland' },
  'IE': { flag: '🇮🇪', name: 'IE', en: 'Ireland' },
  'Ireland': { flag: '🇮🇪', name: 'IE', en: 'Ireland' },

  // 中亚
  '哈萨克斯坦': { flag: '🇰🇿', name: 'KZ', en: 'Kazakhstan' },
  'KZ': { flag: '🇰🇿', name: 'KZ', en: 'Kazakhstan' },
  'Kazakhstan': { flag: '🇰🇿', name: 'KZ', en: 'Kazakhstan' },
  'KAZ': { flag: '🇰🇿', name: 'KZ', en: 'Kazakhstan' },
  '哈国': { flag: '🇰🇿', name: 'KZ', en: 'Kazakhstan' }
} as const

/** 地区代码类型 */
export type RegionCode = keyof typeof REGION_MAP

/** 地区信息类型 */
export type RegionInfo = typeof REGION_MAP[RegionCode]

/** 多城市国家配置（需要显示城市名的国家） */
export const MULTI_CITY_COUNTRIES: Record<string, { short: string; full: string }> = {
  'US': { short: 'USA', full: 'United States' },
  'GB': { short: 'UK', full: 'United Kingdom' },
  'RU': { short: 'Russia', full: 'Russia' },
  'AU': { short: 'Australia', full: 'Australia' },
}

/** 城市映射表 */
export const CITY_MAP: Record<string, { country: string; city: string }> = {
  // 美国城市
  '洛杉矶': { country: 'US', city: 'Los Angeles' },
  'Los Angeles': { country: 'US', city: 'Los Angeles' },
  'LA': { country: 'US', city: 'Los Angeles' },
  '西雅图': { country: 'US', city: 'Seattle' },
  'Seattle': { country: 'US', city: 'Seattle' },
  '圣何塞': { country: 'US', city: 'San Jose' },
  'San Jose': { country: 'US', city: 'San Jose' },
  '硅谷': { country: 'US', city: 'Silicon Valley' },
  'Silicon Valley': { country: 'US', city: 'Silicon Valley' },
  '纽约': { country: 'US', city: 'New York' },
  'New York': { country: 'US', city: 'New York' },
  'NYC': { country: 'US', city: 'New York' },
  '芝加哥': { country: 'US', city: 'Chicago' },
  'Chicago': { country: 'US', city: 'Chicago' },
  '达拉斯': { country: 'US', city: 'Dallas' },
  'Dallas': { country: 'US', city: 'Dallas' },
  '迈阿密': { country: 'US', city: 'Miami' },
  'Miami': { country: 'US', city: 'Miami' },
  '旧金山': { country: 'US', city: 'San Francisco' },
  'San Francisco': { country: 'US', city: 'San Francisco' },
  'SF': { country: 'US', city: 'San Francisco' },
  '华盛顿': { country: 'US', city: 'Washington' },
  'Washington': { country: 'US', city: 'Washington' },
  'DC': { country: 'US', city: 'Washington DC' },
  '凤凰城': { country: 'US', city: 'Phoenix' },
  'Phoenix': { country: 'US', city: 'Phoenix' },
  '丹佛': { country: 'US', city: 'Denver' },
  'Denver': { country: 'US', city: 'Denver' },
  '亚特兰大': { country: 'US', city: 'Atlanta' },
  'Atlanta': { country: 'US', city: 'Atlanta' },

  // 英国城市
  '伦敦': { country: 'GB', city: 'London' },
  'London': { country: 'GB', city: 'London' },
  '考文垂': { country: 'GB', city: 'Coventry' },
  'Coventry': { country: 'GB', city: 'Coventry' },
  '曼彻斯特': { country: 'GB', city: 'Manchester' },
  'Manchester': { country: 'GB', city: 'Manchester' },
  '伯明翰': { country: 'GB', city: 'Birmingham' },
  'Birmingham': { country: 'GB', city: 'Birmingham' },

  // 俄罗斯城市
  '莫斯科': { country: 'RU', city: 'Moscow' },
  'Moscow': { country: 'RU', city: 'Moscow' },
  '圣彼得堡': { country: 'RU', city: 'St. Petersburg' },
  'St. Petersburg': { country: 'RU', city: 'St. Petersburg' },
  'Saint Petersburg': { country: 'RU', city: 'St. Petersburg' },

  // 澳大利亚城市
  '悉尼': { country: 'AU', city: 'Sydney' },
  'Sydney': { country: 'AU', city: 'Sydney' },
  '墨尔本': { country: 'AU', city: 'Melbourne' },
  'Melbourne': { country: 'AU', city: 'Melbourne' },
  '布里斯班': { country: 'AU', city: 'Brisbane' },
  'Brisbane': { country: 'AU', city: 'Brisbane' },
} 