// 国旗图标参考
// 东亚: 🇭🇰 🇨🇳 🇲🇴 🇯🇵 🇰🇷
// 东南亚: 🇸🇬 🇲🇾 🇮🇩 🇹🇭 🇻🇳 🇵🇭
// 南亚: 🇮🇳 🇵🇰 🇧🇩
// 欧洲: 🇬🇧 🇩🇪 🇫🇷 🇮🇹 🇪🇸 🇵🇹 🇳🇱 🇧🇪 🇨🇭 🇸🇪 🇳🇴 🇫🇮 🇩🇰 🇮🇪 🇦🇹 🇵🇱 🇭🇺 🇨🇿 🇧🇬 🇷🇴
// 北美: 🇺🇸 🇨🇦 🇲🇽
// 大洋洲: 🇦🇺 🇳🇿
// 其他: 🇷🇺 🇹🇷 🇧🇷 🇦🇷 🇿🇦 🇮🇱 🇮🇶 🇳🇬

// 地区映射配置
export const REGION_MAP = {
  //图标
  '🇭🇰': { flag: '🇭🇰', name: 'HK', fullName: '香港' },
  '🇨🇳': { flag: '🇨🇳', name: 'TW', fullName: '台湾' },
  '🇲🇴': { flag: '🇲🇴', name: 'MO', fullName: '澳门' },
  '🇯🇵': { flag: '🇯🇵', name: 'JP', fullName: '日本' },
  '🇰🇷': { flag: '🇰🇷', name: 'KR', fullName: '韩国' },
  '🇸🇬': { flag: '🇸🇬', name: 'SG', fullName: '狮城' },
  '🇲🇾': { flag: '🇲🇾', name: 'MY', fullName: '马来西亚' },
  '🇮🇩': { flag: '🇮🇩', name: 'ID', fullName: '印尼' },
  '🇹🇭': { flag: '🇹🇭', name: 'TH', fullName: '泰国' },
  '🇻🇳': { flag: '🇻🇳', name: 'VN', fullName: '越南' },
  '🇵🇭': { flag: '🇵🇭', name: 'PH', fullName: '菲律宾' },
  '🇬🇧': { flag: '🇬🇧', name: 'UK', fullName: '英国' },
  '🇩🇪': { flag: '🇩🇪', name: 'DE', fullName: '德国' },
  '🇫🇷': { flag: '🇫🇷', name: 'FR', fullName: '法国' },
  '🇮🇹': { flag: '🇮🇹', name: 'IT', fullName: '意大利' },
  '🇪🇸': { flag: '🇪🇸', name: 'ES', fullName: '西班牙' },
  '🇺🇸': { flag: '🇺🇸', name: 'US', fullName: '美国' },
  '🇨🇦': { flag: '🇨🇦', name: 'CA', fullName: '加拿大' },
  '🇦🇺': { flag: '🇦🇺', name: 'AU', fullName: '澳大利亚' },
  '🇳🇿': { flag: '🇳🇿', name: 'NZ', fullName: '新西兰' },
  '🇧🇷': { flag: '🇧🇷', name: 'BR', fullName: '圣保罗' },
  // 东亚地区
  '香港': { flag: '🇭🇰', name: 'HK', fullName: '香港' },
  'HK': { flag: '🇭🇰', name: 'HK', fullName: '香港' },
  'Hong Kong': { flag: '🇭🇰', name: 'HK', fullName: '香港' },
  'HKG': { flag: '🇭🇰', name: 'HK', fullName: '香港' },
  '台湾': { flag: '🇨🇳', name: 'TW', fullName: '台湾' },
  'TW': { flag: '🇨🇳', name: 'TW', fullName: '台湾' },
  'Taiwan': { flag: '🇨🇳', name: 'TW', fullName: '台湾' },
  'TWN': { flag: '🇨🇳', name: 'TW', fullName: '台湾' },
  '澳门': { flag: '🇲🇴', name: 'MO', fullName: '澳门' },
  'MO': { flag: '🇲🇴', name: 'MO', fullName: '澳门' },
  'Macao': { flag: '🇲🇴', name: 'MO', fullName: '澳门' },
  '日本': { flag: '🇯🇵', name: 'JP', fullName: '日本' },
  'JP': { flag: '🇯🇵', name: 'JP', fullName: '日本' },
  'Japan': { flag: '🇯🇵', name: 'JP', fullName: '日本' },
  'JPN': { flag: '🇯🇵', name: 'JP', fullName: '日本' },
  '韩国': { flag: '🇰🇷', name: 'KR', fullName: '韩国' },
  'KR': { flag: '🇰🇷', name: 'KR', fullName: '韩国' },
  'Korea': { flag: '🇰🇷', name: 'KR', fullName: '韩国' },
  'KOR': { flag: '🇰🇷', name: 'KR', fullName: '韩国' },

  // 东南亚地区
  '狮城': { flag: '🇸🇬', name: 'SG', fullName: '狮城' },
  '新加坡': { flag: '🇸🇬', name: 'SG', fullName: '狮城' },
  'SG': { flag: '🇸🇬', name: 'SG', fullName: '狮城' },
  'Singapore': { flag: '🇸🇬', name: 'SG', fullName: '狮城' },
  'SGP': { flag: '🇸🇬', name: 'SG', fullName: '狮城' },
  '马来西亚': { flag: '🇲🇾', name: 'MY', fullName: '马来西亚' },
  'MY': { flag: '🇲🇾', name: 'MY', fullName: '马来西亚' },
  'Malaysia': { flag: '🇲🇾', name: 'MY', fullName: '马来西亚' },
  'MYS': { flag: '🇲🇾', name: 'MY', fullName: '马来西亚' },
  '印尼': { flag: '🇮🇩', name: 'ID', fullName: '印尼' },
  '印度尼西亚': { flag: '🇮🇩', name: 'ID', fullName: '印尼' },
  'ID': { flag: '🇮🇩', name: 'ID', fullName: '印尼' },
  'Indonesia': { flag: '🇮🇩', name: 'ID', fullName: '印尼' },
  'IDN': { flag: '🇮🇩', name: 'ID', fullName: '印尼' },
  '泰国': { flag: '🇹🇭', name: 'TH', fullName: '泰国' },
  'TH': { flag: '🇹🇭', name: 'TH', fullName: '泰国' },
  'Thailand': { flag: '🇹🇭', name: 'TH', fullName: '泰国' },
  'THA': { flag: '🇹🇭', name: 'TH', fullName: '泰国' },
  '越南': { flag: '🇻🇳', name: 'VN', fullName: '越南' },
  'VN': { flag: '🇻🇳', name: 'VN', fullName: '越南' },
  'Vietnam': { flag: '🇻🇳', name: 'VN', fullName: '越南' },
  'VNM': { flag: '🇻🇳', name: 'VN', fullName: '越南' },
  '菲律宾': { flag: '🇵🇭', name: 'PH', fullName: '菲律宾' },
  'PH': { flag: '🇵🇭', name: 'PH', fullName: '菲律宾' },
  'Philippines': { flag: '🇵🇭', name: 'PH', fullName: '菲律宾' },
  'PHL': { flag: '🇵🇭', name: 'PH', fullName: '菲律宾' },
  '柬埔寨': { flag: '🇰🇭', name: 'KH', fullName: '柬埔寨' },
  'KH': { flag: '🇰🇭', name: 'KH', fullName: '柬埔寨' },

  // 南亚地区
  '印度': { flag: '🇮🇳', name: 'IN', fullName: '印度' },
  'IN': { flag: '🇮🇳', name: 'IN', fullName: '印度' },
  'India': { flag: '🇮🇳', name: 'IN', fullName: '印度' },
  'IND': { flag: '🇮🇳', name: 'IN', fullName: '印度' },
  '巴基斯坦': { flag: '🇵🇰', name: 'PK', fullName: '巴基斯坦' },
  'PK': { flag: '🇵🇰', name: 'PK', fullName: '巴基斯坦' },
  'Pakistan': { flag: '🇵🇰', name: 'PK', fullName: '巴基斯坦' },
  'PAK': { flag: '🇵🇰', name: 'PK', fullName: '巴基斯坦' },

  // 欧洲地区
  '英国': { flag: '🇬🇧', name: 'UK', fullName: '英国' },
  'UK': { flag: '🇬🇧', name: 'UK', fullName: '英国' },
  'GB': { flag: '🇬🇧', name: 'UK', fullName: '英国' },
  'United Kingdom': { flag: '🇬🇧', name: 'UK', fullName: '英国' },
  'GBR': { flag: '🇬🇧', name: 'UK', fullName: '英国' },
  '德国': { flag: '🇩🇪', name: 'DE', fullName: '德国' },
  'DE': { flag: '🇩🇪', name: 'DE', fullName: '德国' },
  'Germany': { flag: '🇩🇪', name: 'DE', fullName: '德国' },
  'DEU': { flag: '🇩🇪', name: 'DE', fullName: '德国' },
  '法国': { flag: '🇫🇷', name: 'FR', fullName: '法国' },
  'FR': { flag: '🇫🇷', name: 'FR', fullName: '法国' },
  'France': { flag: '🇫🇷', name: 'FR', fullName: '法国' },
  'FRA': { flag: '🇫🇷', name: 'FR', fullName: '法国' },
  '意大利': { flag: '🇮🇹', name: 'IT', fullName: '意大利' },
  'IT': { flag: '🇮🇹', name: 'IT', fullName: '意大利' },
  'Italy': { flag: '🇮🇹', name: 'IT', fullName: '意大利' },
  'ITA': { flag: '🇮🇹', name: 'IT', fullName: '意大利' },
  '西班牙': { flag: '🇪🇸', name: 'ES', fullName: '西班牙' },
  'ES': { flag: '🇪🇸', name: 'ES', fullName: '西班牙' },
  'Spain': { flag: '🇪🇸', name: 'ES', fullName: '西班牙' },
  'ESP': { flag: '🇪🇸', name: 'ES', fullName: '西班牙' },
  '荷兰': { flag: '🇳🇱', name: 'NL', fullName: '荷兰' },
  'NL': { flag: '🇳🇱', name: 'NL', fullName: '荷兰' },
  'Netherlands': { flag: '🇳🇱', name: 'NL', fullName: '荷兰' },
  'NLD': { flag: '🇳🇱', name: 'NL', fullName: '荷兰' },
  '波兰': { flag: '🇵🇱', name: 'PL', fullName: '波兰' },
  'PL': { flag: '🇵🇱', name: 'PL', fullName: '波兰' },
  '乌克兰': { flag: '🇺🇦', name: 'UA', fullName: '乌克兰' },
  'UA': { flag: '🇺🇦', name: 'UA', fullName: '乌克兰' },
  '保加利亚': { flag: '🇧🇬', name: 'BG', fullName: '保加利亚' },
  'BG': { flag: '🇧🇬', name: 'BG', fullName: '保加利亚' },
  'Bulgaria': { flag: '🇧🇬', name: 'BG', fullName: '保加利亚' },
  'BGR': { flag: '🇧🇬', name: 'BG', fullName: '保加利亚' },
  '圣保罗': { flag: '🇧🇷', name: 'BR', fullName: '圣保罗' },
  'SP': { flag: '🇧🇷', name: 'BR', fullName: '圣保罗' },
  'Sao Paulo': { flag: '🇧🇷', name: 'BR', fullName: '圣保罗' },

  // 北欧地区
  '瑞典': { flag: '🇸🇪', name: 'SE', fullName: '瑞典' },
  'SE': { flag: '🇸🇪', name: 'SE', fullName: '瑞典' },
  'Sweden': { flag: '🇸🇪', name: 'SE', fullName: '瑞典' },
  'SWE': { flag: '🇸🇪', name: 'SE', fullName: '瑞典' },
  '挪威': { flag: '🇳🇴', name: 'NO', fullName: '挪威' },
  'NO': { flag: '🇳🇴', name: 'NO', fullName: '挪威' },
  'Norway': { flag: '🇳🇴', name: 'NO', fullName: '挪威' },
  'NOR': { flag: '🇳🇴', name: 'NO', fullName: '挪威' },
  '芬兰': { flag: '🇫🇮', name: 'FI', fullName: '芬兰' },
  'FI': { flag: '🇫🇮', name: 'FI', fullName: '芬兰' },
  '丹麦': { flag: '🇩🇰', name: 'DK', fullName: '丹麦' },
  'DK': { flag: '🇩🇰', name: 'DK', fullName: '丹麦' },
  '冰岛': { flag: '🇮🇸', name: 'IS', fullName: '冰岛' },
  'IS': { flag: '🇮🇸', name: 'IS', fullName: '冰岛' },

  // 北美地区
  '美国': { flag: '🇺🇸', name: 'US', fullName: '美国' },
  'US': { flag: '🇺🇸', name: 'US', fullName: '美国' },
  'USA': { flag: '🇺🇸', name: 'US', fullName: '美国' },
  'United States': { flag: '🇺🇸', name: 'US', fullName: '美国' },
  '加拿大': { flag: '🇨🇦', name: 'CA', fullName: '加拿大' },
  'CA': { flag: '🇨🇦', name: 'CA', fullName: '加拿大' },
  'Canada': { flag: '🇨🇦', name: 'CA', fullName: '加拿大' },
  'CAN': { flag: '🇨🇦', name: 'CA', fullName: '加拿大' },
  '墨西哥': { flag: '🇲🇽', name: 'MX', fullName: '墨西哥' },
  'MX': { flag: '🇲🇽', name: 'MX', fullName: '墨西哥' },
  'Mexico': { flag: '🇲🇽', name: 'MX', fullName: '墨西哥' },
  'MEX': { flag: '🇲🇽', name: 'MX', fullName: '墨西哥' },

  // 大洋洲
  '澳大利亚': { flag: '🇦🇺', name: 'AU', fullName: '澳大利亚' },
  'AU': { flag: '🇦🇺', name: 'AU', fullName: '澳大利亚' },
  'Australia': { flag: '🇦🇺', name: 'AU', fullName: '澳大利亚' },
  'AUS': { flag: '🇦🇺', name: 'AU', fullName: '澳大利亚' },
  '新西兰': { flag: '🇳🇿', name: 'NZ', fullName: '新西兰' },
  'NZ': { flag: '🇳🇿', name: 'NZ', fullName: '新西兰' },
  'New Zealand': { flag: '🇳🇿', name: 'NZ', fullName: '新西兰' },
  'NZL': { flag: '🇳🇿', name: 'NZ', fullName: '新西兰' },

  // 其他地区
  '俄罗斯': { flag: '🇷🇺', name: 'RU', fullName: '俄罗斯' },
  'RU': { flag: '🇷🇺', name: 'RU', fullName: '俄罗斯' },
  'Russia': { flag: '🇷🇺', name: 'RU', fullName: '俄罗斯' },
  'RUS': { flag: '🇷🇺', name: 'RU', fullName: '俄罗斯' },
  '土耳其': { flag: '🇹🇷', name: 'TR', fullName: '土耳其' },
  'TR': { flag: '🇹🇷', name: 'TR', fullName: '土耳其' },
  'Turkey': { flag: '🇹🇷', name: 'TR', fullName: '土耳其' },
  'TUR': { flag: '🇹🇷', name: 'TR', fullName: '土耳其' },
  '巴西': { flag: '🇧🇷', name: 'BR', fullName: '巴西' },
  'BR': { flag: '🇧🇷', name: 'BR', fullName: '巴西' },
  'Brazil': { flag: '🇧🇷', name: 'BR', fullName: '巴西' },
  'BRA': { flag: '🇧🇷', name: 'BR', fullName: '巴西' },
  '阿根廷': { flag: '🇦🇷', name: 'AR', fullName: '阿根廷' },
  'AR': { flag: '🇦🇷', name: 'AR', fullName: '阿根廷' },
  '南非': { flag: '🇿🇦', name: 'ZA', fullName: '南非' },
  'ZA': { flag: '🇿🇦', name: 'ZA', fullName: '南非' },
  '以色列': { flag: '🇮🇱', name: 'IL', fullName: '以色列' },
  'IL': { flag: '🇮🇱', name: 'IL', fullName: '以色列' },
  '伊拉克': { flag: '🇮🇶', name: 'IQ', fullName: '伊拉克' },
  'IQ': { flag: '🇮🇶', name: 'IQ', fullName: '伊拉克' },
  '尼日利亚': { flag: '🇳🇬', name: 'NG', fullName: '尼日利亚' },
  'NG': { flag: '🇳🇬', name: 'NG', fullName: '尼日利亚' },
  '瑞士': { flag: '🇨🇭', name: 'CH', fullName: '瑞士' },
} as const

// 导出类型
export type RegionCode = keyof typeof REGION_MAP
export type RegionInfo = typeof REGION_MAP[RegionCode] 